package com.example.translator

enum class ModelType(private val pathName: String) {
    BASE("base"),
    BASE_MEMORY("base-memory"),
    TINY("tiny");

    override fun toString(): String = pathName
}

enum class Language(val code: String, val displayName: String) {
    ALBANIAN("sq", "Albanian"),
    ARABIC("ar", "Arabic"),
    AZERBAIJANI("az", "Azerbaijani"),
    BELARUSIAN("be", "Belarusian"),
    BENGALI("bn", "Bengali"),
    BOSNIAN("bs", "Bosnian"),
    BULGARIAN("bg", "Bulgarian"),
    CATALAN("ca", "Catalan"),
    CHINESE("zh", "Chinese"),
    CROATIAN("hr", "Croatian"),
    CZECH("cs", "Czech"),
    DANISH("da", "Danish"),
    DUTCH("nl", "Dutch"),
    ENGLISH("en", "English"),
    ESTONIAN("et", "Estonian"),
    FINNISH("fi", "Finnish"),
    FRENCH("fr", "French"),
    GERMAN("de", "German"),
    GREEK("el", "Greek"),
    GUJARATI("gu", "Gujarati"),
    HEBREW("he", "Hebrew"),
    HINDI("hi", "Hindi"),
    HUNGARIAN("hu", "Hungarian"),
    ICELANDIC("is", "Icelandic"),
    INDONESIAN("id", "Indonesian"),
    ITALIAN("it", "Italian"),
    JAPANESE("ja", "Japanese"),
    KANNADA("kn", "Kannada"),
    KOREAN("ko", "Korean"),
    LATVIAN("lv", "Latvian"),
    LITHUANIAN("lt", "Lithuanian"),
    MALAY("ms", "Malay"),
    MALAYALAM("ml", "Malayalam"),
    MALTESE("mt", "Maltese"),
    NORWEGIAN_BOKMAL("nb", "Norwegian Bokmål"),
    NORWEGIAN_NYNORSK("nn", "Norwegian Nynorsk"),
    PERSIAN("fa", "Persian"),
    POLISH("pl", "Polish"),
    PORTUGUESE("pt", "Portuguese"),
    ROMANIAN("ro", "Romanian"),
    RUSSIAN("ru", "Russian"),
    SERBIAN("sr", "Serbian"),
    SLOVAK("sk", "Slovak"),
    SLOVENIAN("sl", "Slovenian"),
    SPANISH("es", "Spanish"),
    SWEDISH("sv", "Swedish"),
    TAMIL("ta", "Tamil"),
    TELUGU("te", "Telugu"),
    TURKISH("tr", "Turkish"),
    UKRAINIAN("uk", "Ukrainian"),
    VIETNAMESE("vi", "Vietnamese")
}




val fromEnglish = mapOf(
    Language.ARABIC to ModelType.BASE,
    Language.BULGARIAN to ModelType.TINY,
    Language.CATALAN to ModelType.BASE_MEMORY,
    Language.CZECH to ModelType.BASE,
    Language.DANISH to ModelType.TINY,
    Language.GERMAN to ModelType.TINY,
    Language.GREEK to ModelType.TINY,
    Language.SPANISH to ModelType.TINY,
    Language.ESTONIAN to ModelType.TINY,
    Language.PERSIAN to ModelType.TINY,
    Language.FINNISH to ModelType.TINY,
    Language.FRENCH to ModelType.TINY,
    Language.CROATIAN to ModelType.TINY,
    Language.HUNGARIAN to ModelType.BASE_MEMORY,
    Language.INDONESIAN to ModelType.TINY,
    Language.ITALIAN to ModelType.TINY,
    Language.JAPANESE to ModelType.BASE,
    Language.KOREAN to ModelType.BASE,
    Language.LITHUANIAN to ModelType.BASE_MEMORY,
    Language.LATVIAN to ModelType.BASE_MEMORY,
    Language.DUTCH to ModelType.TINY,
    Language.POLISH to ModelType.TINY,
    Language.PORTUGUESE to ModelType.TINY,
    Language.ROMANIAN to ModelType.TINY,
    Language.RUSSIAN to ModelType.BASE,
    Language.SLOVAK to ModelType.BASE_MEMORY,
    Language.SLOVENIAN to ModelType.BASE_MEMORY,
    Language.SWEDISH to ModelType.TINY,
    Language.TURKISH to ModelType.TINY,
    Language.UKRAINIAN to ModelType.BASE_MEMORY,
    Language.CHINESE to ModelType.BASE
)

val toEnglish = mapOf(
    Language.ARABIC to ModelType.BASE,
    Language.AZERBAIJANI to ModelType.TINY,
    Language.BELARUSIAN to ModelType.TINY,
    Language.BULGARIAN to ModelType.TINY,
    Language.BENGALI to ModelType.TINY,
    Language.BOSNIAN to ModelType.TINY,
    Language.CATALAN to ModelType.BASE_MEMORY,
    Language.CZECH to ModelType.TINY,
    Language.DANISH to ModelType.TINY,
    Language.GERMAN to ModelType.BASE,
    Language.GREEK to ModelType.TINY,
    Language.SPANISH to ModelType.TINY,
    Language.ESTONIAN to ModelType.TINY,
    Language.PERSIAN to ModelType.TINY,
    Language.FINNISH to ModelType.TINY,
    Language.FRENCH to ModelType.TINY,
    Language.GUJARATI to ModelType.TINY,
    Language.HEBREW to ModelType.TINY,
    Language.HINDI to ModelType.TINY,
    Language.CROATIAN to ModelType.TINY,
    Language.HUNGARIAN to ModelType.TINY,
    Language.INDONESIAN to ModelType.TINY,
    Language.ICELANDIC to ModelType.TINY,
    Language.ITALIAN to ModelType.TINY,
    Language.JAPANESE to ModelType.BASE,
    Language.KANNADA to ModelType.TINY,
    Language.KOREAN to ModelType.BASE,
    Language.LITHUANIAN to ModelType.TINY,
    Language.LATVIAN to ModelType.TINY,
    Language.MALAYALAM to ModelType.TINY,
    Language.MALAY to ModelType.TINY,
    Language.MALTESE to ModelType.TINY,
    Language.NORWEGIAN_BOKMAL to ModelType.TINY,
    Language.DUTCH to ModelType.BASE_MEMORY,
    Language.NORWEGIAN_NYNORSK to ModelType.TINY,
    Language.POLISH to ModelType.TINY,
    Language.PORTUGUESE to ModelType.TINY,
    Language.ROMANIAN to ModelType.TINY,
    Language.RUSSIAN to ModelType.TINY,
    Language.SLOVAK to ModelType.TINY,
    Language.SLOVENIAN to ModelType.BASE_MEMORY,
    Language.ALBANIAN to ModelType.TINY,
    Language.SERBIAN to ModelType.TINY,
    Language.SWEDISH to ModelType.TINY,
    Language.TAMIL to ModelType.TINY,
    Language.TELUGU to ModelType.TINY,
    Language.TURKISH to ModelType.TINY,
    Language.UKRAINIAN to ModelType.TINY,
    Language.VIETNAMESE to ModelType.TINY,
    Language.CHINESE to ModelType.BASE
)