package dev.davidv.translator

enum class ModelType(private val pathName: String) {
    BASE("base"),
    BASE_MEMORY("base-memory"),
    TINY("tiny");

    override fun toString(): String = pathName
}

enum class Language(val code: String, val tessName: String, val displayName: String) {
    ALBANIAN("sq", "sqi", "Albanian"),
    ARABIC("ar", "ara", "Arabic"),
    AZERBAIJANI("az", "aze", "Azerbaijani"),
    BELARUSIAN("be", "bel", "Belarusian"),
    BENGALI("bn", "ben", "Bengali"),
    BOSNIAN("bs", "bos", "Bosnian"),
    BULGARIAN("bg", "bul", "Bulgarian"),
    CATALAN("ca", "cat", "Catalan"),
    CHINESE("zh", "chi_sim", "Chinese"),
    CROATIAN("hr", "hrv", "Croatian"),
    CZECH("cs", "ces", "Czech"),
    DANISH("da", "dan", "Danish"),
    DUTCH("nl", "nld", "Dutch"),
    ENGLISH("en", "eng", "English"),
    ESTONIAN("et", "est", "Estonian"),
    FINNISH("fi", "fin", "Finnish"),
    FRENCH("fr", "fra", "French"),
    GERMAN("de", "deu", "German"),
    GREEK("el", "ell", "Greek"),
    GUJARATI("gu", "guj", "Gujarati"),
    HEBREW("he", "heb", "Hebrew"),
    HINDI("hi", "hin", "Hindi"),
    HUNGARIAN("hu", "hun", "Hungarian"),
    ICELANDIC("is", "isl", "Icelandic"),
    INDONESIAN("id", "ind", "Indonesian"),
    ITALIAN("it", "ita", "Italian"),
    JAPANESE("ja", "jpn", "Japanese"),
    KANNADA("kn", "kan", "Kannada"),
    KOREAN("ko", "kor", "Korean"),
    LATVIAN("lv", "lav", "Latvian"),
    LITHUANIAN("lt", "lit", "Lithuanian"),
    MALAY("ms", "msa", "Malay"),
    MALAYALAM("ml", "mal", "Malayalam"),
    MALTESE("mt", "mlt", "Maltese"),
    NORWEGIAN_BOKMAL("nb", "nor", "Norwegian Bokmål"),
    NORWEGIAN_NYNORSK("nn", "nor", "Norwegian Nynorsk"),
    PERSIAN("fa", "fas", "Persian"),
    POLISH("pl", "pol", "Polish"),
    PORTUGUESE("pt", "por", "Portuguese"),
    ROMANIAN("ro", "ron", "Romanian"),
    RUSSIAN("ru", "rus", "Russian"),
    SERBIAN("sr", "srp", "Serbian"),
    SLOVAK("sk", "slk", "Slovak"),
    SLOVENIAN("sl", "slv", "Slovenian"),
    SPANISH("es", "spa", "Spanish"),
    SWEDISH("sv", "swe", "Swedish"),
    TAMIL("ta", "tam", "Tamil"),
    TELUGU("te", "tel", "Telugu"),
    TURKISH("tr", "tur", "Turkish"),
    UKRAINIAN("uk", "ukr", "Ukrainian"),
    VIETNAMESE("vi", "vie", "Vietnamese")
}

val fromEnglish = mapOf(
    Language.ARABIC to ModelType.BASE,
    Language.BULGARIAN to ModelType.TINY,
    Language.BENGALI to ModelType.TINY,
    Language.CATALAN to ModelType.BASE_MEMORY,
    Language.CZECH to ModelType.BASE,
    Language.DANISH to ModelType.TINY,
    Language.GERMAN to ModelType.TINY,
    Language.GREEK to ModelType.TINY,
    Language.SPANISH to ModelType.TINY,
    Language.ESTONIAN to ModelType.TINY,
    Language.PERSIAN to ModelType.TINY,
    Language.FINNISH to ModelType.TINY,
    Language.FRENCH to ModelType.TINY,
    Language.GUJARATI to ModelType.TINY,
    Language.HEBREW to ModelType.TINY,
    Language.HINDI to ModelType.TINY,
    Language.CROATIAN to ModelType.TINY,
    Language.HUNGARIAN to ModelType.BASE_MEMORY,
    Language.INDONESIAN to ModelType.TINY,
    Language.ITALIAN to ModelType.TINY,
    Language.JAPANESE to ModelType.BASE,
    Language.KANNADA to ModelType.TINY,
    Language.KOREAN to ModelType.BASE,
    Language.LITHUANIAN to ModelType.BASE_MEMORY,
    Language.LATVIAN to ModelType.BASE_MEMORY,
    Language.MALAYALAM to ModelType.TINY,
    Language.MALAY to ModelType.TINY,
    Language.DUTCH to ModelType.TINY,
    Language.POLISH to ModelType.TINY,
    Language.PORTUGUESE to ModelType.TINY,
    Language.ROMANIAN to ModelType.TINY,
    Language.RUSSIAN to ModelType.BASE,
    Language.SLOVAK to ModelType.BASE_MEMORY,
    Language.SLOVENIAN to ModelType.BASE_MEMORY,
    Language.ALBANIAN to ModelType.TINY,
    Language.SWEDISH to ModelType.TINY,
    Language.TAMIL to ModelType.TINY,
    Language.TELUGU to ModelType.TINY,
    Language.TURKISH to ModelType.TINY,
    Language.UKRAINIAN to ModelType.BASE_MEMORY,
    Language.CHINESE to ModelType.BASE
)

val toEnglish = mapOf(
    Language.ARABIC to ModelType.BASE,
    Language.BULGARIAN to ModelType.TINY,
    Language.BENGALI to ModelType.TINY,
    Language.CATALAN to ModelType.BASE_MEMORY,
    Language.CZECH to ModelType.TINY,
    Language.DANISH to ModelType.TINY,
    Language.GERMAN to ModelType.BASE,
    Language.GREEK to ModelType.TINY,
    Language.SPANISH to ModelType.TINY,
    Language.ESTONIAN to ModelType.TINY,
    Language.PERSIAN to ModelType.TINY,
    Language.FINNISH to ModelType.TINY,
    Language.FRENCH to ModelType.TINY,
    Language.GUJARATI to ModelType.TINY,
    Language.HEBREW to ModelType.TINY,
    Language.HINDI to ModelType.TINY,
    Language.CROATIAN to ModelType.TINY,
    Language.HUNGARIAN to ModelType.TINY,
    Language.INDONESIAN to ModelType.TINY,
    Language.ITALIAN to ModelType.TINY,
    Language.JAPANESE to ModelType.BASE,
    Language.KANNADA to ModelType.TINY,
    Language.KOREAN to ModelType.BASE,
    Language.LITHUANIAN to ModelType.TINY,
    Language.LATVIAN to ModelType.TINY,
    Language.MALAYALAM to ModelType.TINY,
    Language.MALAY to ModelType.TINY,
    Language.DUTCH to ModelType.BASE_MEMORY,
    Language.POLISH to ModelType.TINY,
    Language.PORTUGUESE to ModelType.TINY,
    Language.ROMANIAN to ModelType.TINY,
    Language.RUSSIAN to ModelType.TINY,
    Language.SLOVAK to ModelType.TINY,
    Language.SLOVENIAN to ModelType.BASE_MEMORY,
    Language.ALBANIAN to ModelType.TINY,
    Language.SWEDISH to ModelType.TINY,
    Language.TAMIL to ModelType.TINY,
    Language.TELUGU to ModelType.TINY,
    Language.TURKISH to ModelType.TINY,
    Language.UKRAINIAN to ModelType.TINY,
    Language.CHINESE to ModelType.BASE
)