name: Build Android App

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
    inputs:
      build_type:
        type: choice
        description: 'Build Type:'
        options:
          - 'release'
          - 'debug'
        default: 'debug'
      build_os_version:
        type: choice
        description: 'Choice a os build version machine:'
        options:
          - 'ubuntu-latest'
          - 'ubuntu-24.04'
          - 'ubuntu-22.04'
        default: 'ubuntu-latest'
jobs:
  build:
    runs-on: ${{ github.event.inputs.build_os_version }}
    outputs:
      short_sha: ${{ steps.set_sha.outputs.short_sha }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    
    - name: Build Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: false
        load: true
        tags: translator-app:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max
    
    - name: Run build in container
      run: |
        docker run --rm \
          -v ${{ github.workspace }}:/home/vagrant/build/dev.davidv.translator/ \
          --user $(id -u):$(id -g) \
          translator-app:latest \
          ./gradlew assembleAarch64Release \
          ls app/build/outputs/apk/**/*.apk
          
    - name: Set short SHA
      id: set_sha
      run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Rename APK with commit hash
      run: |
          mv app/build/outputs/apk/**/*.apk \
             app/build/outputs/apk/**/app-release-${{ steps.set_sha.outputs.short_sha }}.apk

    - name: Upload APK artifacts
      uses: actions/upload-artifact@v4
      with:
        name: apk-files
        path: app/build/outputs/apk/**/app-release-${{ steps.set_sha.outputs.short_sha }}.apk
        retention-days: 30
